#pragma once

#ifndef PEBMONITOR_KERNEL_SHARED
#include <windows.h>
#include <winioctl.h>
#endif

#define MAX_RULE_LENGTH 256
#define MAX_RULE_ID_LENGTH 128
#define MAX_REG_PATH_LENGTH 512
#define MAX_EVENT_COMMAND_LINE_LENGTH 256
#define MAX_REGISTRY_RULE_COUNT 256

#define PEBMONITOR_ABI_VERSION 4UL
#define PEBMONITOR_ABI_IS_COMPAT(v) ((v) == PEBMONITOR_ABI_VERSION)

#define PEB_MONITOR_DEVICE 0x8000
#define IOCTL_GET_DRIVER_EVENT CTL_CODE(PEB_MONITOR_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_REGISTRY_RULE CTL_CODE(PEB_MONITOR_DEVICE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_REGISTRY_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_REGISTRY_ALLOW_RULE CTL_CODE(PEB_MONITOR_DEVICE, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_REGISTRY_ALLOW_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUERY_DRIVER_STATUS CTL_CODE(PEB_MONITOR_DEVICE, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_ACTIVE_CONFIG_INFO CTL_CODE(PEB_MONITOR_DEVICE, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HIPS_HEARTBEAT CTL_CODE(PEB_MONITOR_DEVICE, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_EDR_TERMINATE_PROCESS CTL_CODE(PEB_MONITOR_DEVICE, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REPLACE_REGISTRY_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REPLACE_REGISTRY_ALLOW_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x80F, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PEBMONITOR_PROCESS_PORT_NAME L"\\PebMonitorProcessPort"
#define PROCESS_PORT_PROTOCOL_VERSION 3UL
#define PROCESS_PORT_REQUEST_FLAG_FILE_OPEN_NAME_AVAILABLE 0x0001UL
#define PROCESS_VERDICT_TIMEOUT_MS_DEFAULT 1000UL
#define PROCESS_VERDICT_TIMEOUT_MS_MIN 100UL
#define PROCESS_VERDICT_TIMEOUT_MS_MAX 10000UL
#define PROCESS_VERDICT_FAIL_OPEN 1UL
#define PROCESS_VERDICT_FAIL_CLOSE 2UL
#define PROCESS_HEARTBEAT_INTERVAL_MS_DEFAULT 1000UL
#define PROCESS_HEARTBEAT_TIMEOUT_MS_DEFAULT 5000UL
#define PROCESS_PARENT_CMDLINE_CAPTURE_DISABLED 0UL
#define PROCESS_PARENT_CMDLINE_CAPTURE_ENABLED 1UL

#define DRIVER_STATUS_FLAG_DEVICE_READY 0x0001UL
#define DRIVER_STATUS_FLAG_PROCESS_CALLBACK_REGISTERED 0x0002UL
#define DRIVER_STATUS_FLAG_REGISTRY_CALLBACK_REGISTERED 0x0008UL
#define DRIVER_STATUS_FLAG_PROCESS_PORT_CONNECTED 0x0020UL
#define DRIVER_STATUS_FLAG_PROCESS_BREAKER_OPEN 0x0040UL
#define DRIVER_STATUS_FLAG_MONITOR_ONLY 0x0080UL

#define DRIVER_EVENT_TYPE_BLOCKED_REGISTRY_OPERATION 3UL
#define DRIVER_EVENT_TYPE_OBSERVED_REGISTRY_OPERATION 4UL
#define DRIVER_EVENT_TYPE_BLOCKED_REGISTRY_SET DRIVER_EVENT_TYPE_BLOCKED_REGISTRY_OPERATION
#define DRIVER_EVENT_TYPE_RESPONSE_ACTION 5UL
#define DRIVER_EVENT_TYPE_OBSERVED_PROCESS_CREATE 6UL
#define DRIVER_EVENT_TYPE_BLOCKED_FILE_OPERATION 7UL

#define RESPONSE_ACTION_TERMINATE_PROCESS 1UL

#define REGISTRY_OPERATION_SET_VALUE 1UL
#define REGISTRY_OPERATION_CREATE_KEY 2UL
#define REGISTRY_OPERATION_DELETE_VALUE 3UL
#define REGISTRY_OPERATION_DELETE_KEY 4UL
#define REGISTRY_OPERATION_RENAME_KEY 5UL
#define REGISTRY_OPERATION_SET_INFORMATION_KEY 6UL

#define REGISTRY_MATCH_FLAG_PROCESS_NAME 0x0001UL
#define REGISTRY_MATCH_FLAG_KEY_PATH 0x0002UL
#define REGISTRY_MATCH_FLAG_VALUE_NAME 0x0004UL
#define REGISTRY_MATCH_FLAG_VALUE_DATA 0x0008UL
#define REGISTRY_MATCH_FLAG_INFO_CLASS 0x0010UL

#define REGISTRY_MATCH_TYPE_EXACT 1UL
#define REGISTRY_MATCH_TYPE_PREFIX 2UL
#define REGISTRY_MATCH_TYPE_SUFFIX 3UL
#define REGISTRY_MATCH_TYPE_CONTAINS 4UL

typedef enum _HIPS_PROTECTION_MODE {
    HIPS_MODE_MONITOR_ONLY = 0,
    HIPS_MODE_BLOCKING = 1
} HIPS_PROTECTION_MODE, *PHIPS_PROTECTION_MODE;

typedef struct _PROCESS_PORT_REQUEST {
    ULONG Version;
    ULONG Flags;
    ULONG64 EventId;
    ULONG64 CreateTime;
    ULONG ProcessId;
    ULONG ParentProcessId;
    WCHAR ImagePath[MAX_REG_PATH_LENGTH];
    WCHAR ParentImagePath[MAX_REG_PATH_LENGTH];
    WCHAR CommandLine[1024];
    WCHAR ParentCommandLine[1024];
} PROCESS_PORT_REQUEST, *PPROCESS_PORT_REQUEST;

typedef struct _PROCESS_PORT_REPLY {
    ULONG Version;
    ULONG BlockProcess;
} PROCESS_PORT_REPLY, *PPROCESS_PORT_REPLY;

typedef struct _EDR_TERMINATE_PROCESS_REQUEST {
    ULONG ProcessId;
    LONG ExitStatus;
} EDR_TERMINATE_PROCESS_REQUEST, *PEDR_TERMINATE_PROCESS_REQUEST;

typedef struct _DRIVER_EVENT {
    ULONG EventType;
    ULONG ProcessId;
    ULONG ParentProcessId;
    ULONG Severity;
    ULONG RegistryOperation;
    ULONG ResponseAction;
    LONG ResponseStatus;
    WCHAR ProcessName[MAX_RULE_LENGTH];
    WCHAR CommandLine[MAX_EVENT_COMMAND_LINE_LENGTH];
    WCHAR RuleId[MAX_RULE_ID_LENGTH];
    WCHAR TargetPath[MAX_REG_PATH_LENGTH];
    WCHAR InfoClass[MAX_RULE_LENGTH];
    WCHAR ValueName[MAX_RULE_LENGTH];
    WCHAR ValueData[MAX_RULE_LENGTH];
} DRIVER_EVENT, *PDRIVER_EVENT;

typedef struct _REGISTRY_RULE {
    ULONG Operation;
    ULONG MatchFlags;
    ULONG Severity;
    ULONG ProcessNameMatchType;
    WCHAR ProcessName[MAX_RULE_LENGTH];
    ULONG KeyPathMatchType;
    WCHAR KeyPath[MAX_REG_PATH_LENGTH];
    ULONG InfoClassMatchType;
    WCHAR InfoClass[MAX_RULE_LENGTH];
    ULONG ValueNameMatchType;
    WCHAR ValueName[MAX_RULE_LENGTH];
    ULONG ValueDataMatchType;
    WCHAR ValueData[MAX_RULE_LENGTH];
    WCHAR RuleId[MAX_RULE_ID_LENGTH];
} REGISTRY_RULE, *PREGISTRY_RULE;

typedef struct _REGISTRY_RULE_BATCH_UPDATE {
    ULONG AbiVersion;
    ULONG RuleCount;
    REGISTRY_RULE Rules[ANYSIZE_ARRAY];
} REGISTRY_RULE_BATCH_UPDATE, *PREGISTRY_RULE_BATCH_UPDATE;

typedef struct _DRIVER_CONFIG_INFO {
    WCHAR ConfigVersion[MAX_RULE_LENGTH];
    WCHAR ProfileName[MAX_RULE_LENGTH];
    WCHAR GeneratedAt[MAX_RULE_LENGTH];
    ULONG ProcessVerdictTimeoutMs;
    ULONG ProcessVerdictFailMode;
    ULONG CaptureParentCommandLine;
} DRIVER_CONFIG_INFO, *PDRIVER_CONFIG_INFO;

typedef struct _DRIVER_RUNTIME_STATUS {
    ULONG AbiVersion;
    ULONG StatusFlags;
    ULONG ProtectionMode;
    ULONG PolicyEpoch;
    ULONG RegistryRuleCount;
    ULONG RegistryAllowRuleCount;
    ULONG RegistryRuleExactCount;
    ULONG RegistryRulePrefixCount;
    ULONG RegistryRuleSuffixCount;
    ULONG RegistryRuleContainsCount;
    ULONG RegistryAllowRuleExactCount;
    ULONG RegistryAllowRulePrefixCount;
    ULONG RegistryAllowRuleSuffixCount;
    ULONG RegistryAllowRuleContainsCount;
    ULONG DriverEventQueueCount;
    ULONGLONG DriverEventDropCount;
    ULONGLONG DriverEventAllocFailCount;
    ULONGLONG FastPathHitCount;
    ULONGLONG CacheHitCount;
    ULONGLONG CacheMissCount;
    ULONGLONG CacheFlushCount;
    ULONGLONG SlowPathCount;
    ULONG64 ProcessVerdictRequestCount;
    ULONG64 ProcessVerdictTimeoutCount;
    ULONG64 ProcessPortConnectCount;
    ULONG64 ProcessPortDisconnectCount;
    ULONG64 LastProcessPortConnectTime;
    ULONG64 LastProcessPortDisconnectTime;
    ULONG64 LastProcessVerdictTimeoutTime;
    ULONG64 LastHeartbeatTime;
    ULONG64 ProcessBreakerOpenCount;
    ULONG64 LastProcessBreakerOpenTime;
    ULONG64 LastProcessBreakerCloseTime;
    ULONG ProcessVerdictTimeoutMs;
    ULONG ProcessVerdictFailMode;
    ULONG HeartbeatIntervalMs;
    ULONG HeartbeatTimeoutMs;
    ULONG CaptureParentCommandLine;
    WCHAR ConfigVersion[MAX_RULE_LENGTH];
    WCHAR ProfileName[MAX_RULE_LENGTH];
    WCHAR GeneratedAt[MAX_RULE_LENGTH];
} DRIVER_RUNTIME_STATUS, *PDRIVER_RUNTIME_STATUS;

static_assert(sizeof(PROCESS_PORT_REQUEST) == 6176, "Unexpected PROCESS_PORT_REQUEST size");
static_assert(sizeof(PROCESS_PORT_REPLY) == 8, "Unexpected PROCESS_PORT_REPLY size");
static_assert(sizeof(EDR_TERMINATE_PROCESS_REQUEST) == 8, "Unexpected EDR_TERMINATE_PROCESS_REQUEST size");
static_assert(sizeof(DRIVER_EVENT) == 3868, "Unexpected DRIVER_EVENT size");
static_assert(sizeof(REGISTRY_RULE) == 3360, "Unexpected REGISTRY_RULE size");
static_assert(FIELD_OFFSET(REGISTRY_RULE_BATCH_UPDATE, Rules) == 8, "Unexpected REGISTRY_RULE_BATCH_UPDATE header size");
static_assert(sizeof(DRIVER_CONFIG_INFO) == 1548, "Unexpected DRIVER_CONFIG_INFO size");
static_assert(FIELD_OFFSET(DRIVER_RUNTIME_STATUS, AbiVersion) == 0, "AbiVersion must remain at offset 0");
static_assert(sizeof(DRIVER_RUNTIME_STATUS) == 1768, "Unexpected DRIVER_RUNTIME_STATUS size");
